name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: List all files
      shell: cmd
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC" /s
        
    - name: Copy all files
      shell: cmd
      run: |
        mkdir upload
        xcopy /y /v /s /e "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC" upload
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
