name: Remove v143

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Remove Visual Studio toolset v143
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify ^
        --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" ^
        --remove Microsoft.VisualStudio.Workload.NativeDesktop ^
        --passive

    - name: List directories
      shell: cmd
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\"
