name: Install v141

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Install Visual Studio toolset
      shell: cmd
      run: |
        mkdir C:\vsupdate
        "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify --installPath C:\vsupdate --channelId VisualStudio.15.Release --quiet --includeRecommended --add Microsoft.VisualStudio.Component.VC.v141.x86.x64

    - name: List directories
      shell: cmd
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\"
