name: V1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Install Visual Studio toolset
      shell: cmd
      run: |
        cd VS2017
        vs_enterprise.exe --layout C:\VSLayout --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --lang en-US
